server:
  port: 8090

spring:
  data:
    mongodb:
      database: customer
      username: taihuynh
      password: password
      authentication-database: admin
      host: localhost
      port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost