spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: taihuynh
    password: taihuynh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.taihuynh.ecommerce.kafka.PaymentNotificationRequest

server:
  port: 8060