spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: taihuynh
    password: taihuynh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 1
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    clean-disabled: false
    clean-on-validation-error: true

server:
  port: 8050